### ISSUE TITLE
Translation loading trigerred too early

### ISSUE THREAD

**Issue by Ilhamkang** [cssigniter/audioigniter#1]
Dear developer, 

Recently I got this notification in my self-hosted Wordpress, running Audio Igniter plugin. 

`Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the audioigniter domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /home/username/domains/domainname.org/public_html/wp-includes/functions.php on line 6114` 

Could you identify why this is happended? and if there is any solution I will be happy to know it.

**Comment by anastis** [comment]
Hi there,
thanks for reporting this.
Yes, this is due to a change in WP 6.7. We'll provide an update soon.

For now, you can set WP_DEBUG to false (it's not recommended for production websites anyway).

**Comment by Ilhamkang** [comment]
Thanks for the fix and update!

**Comment by anastis** [comment]
I've just released an update to the wp.org repository, so you can update normally.
